baseURL         = ""
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Arqam's Site"
  subtitle    = "My Awesome Site"

  cover       = "img/blog-cover.jpg"
  description = "Arqam's Awesome Site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "arqambinrehan"
  fbName = "arqambinrehan"
  githubName = "arqambinrehan"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "arqambinrehan"
  authorAvatar = "img/profile-pic.jpg"
  authorLocation = "Lahore"
  authorWebsite = "https://arqambinrehan.github.io"
  authorDescription = "Developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "#"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/project/"
  weight = 100

[[menu.main]]
  name = "My Life"
  url = "/categories/life/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95